### PR TITLE
WIP: Use k8s APIs generated by openapi-generator

### PR DESCRIPTION
**Pull request by ynqa**
### Overview

- Use kubernetes APIs generated by openapi-generator, instead of [k8s-openapi-codegen](https://github.com/Arnavion/k8s-openapi-codegen).

### CODE REVIEW

**Comment by ngortheone** [comment]
Hi @ynqa, I have very limited experience with rust, can you explain the motivation behind this PR?
In other words why not just importing things from https://github.com/Arnavion/k8s-openapi-codegen and using them?

**Comment by ynqa** [comment]
@ngortheone I'm considering to give [kubernetes-client](https://github.com/kubernetes-client) org this client. But they probably don't accept k8s APIs generated by custom generators, instead of [kubernetes-client/gen](https://github.com/kubernetes-client/gen) with original swagger-codegen/openapi-generator.

**Comment by ngortheone** [comment]
Are there any prescriptive guidelines / acceptance criteria for moving client to kubernetes-client org?

**Comment by ynqa** [comment]
@ngortheone Nope. So I directly heard them 1). [Bronze requirements](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md#client-capabilities) was satisfied. 2). Generate k8s APIs by [kubernetes-client/gen](https://github.com/kubernetes-client/gen).

**Comment by ynqa** [comment]
It will be closed and continue to work on `openapi-gen` branch for kubernetes-client org.

**Comment by Arnavion** [comment]
(I've added https://github.com/Arnavion/k8s-openapi/blob/master/README.md to talk about why generic generators like swagger and openapi will find it hard to provide a nice API compared to manual, Kubernetes-specific generation.)

**Comment by ynqa** [comment]
@Arnavion Thanks for your comments!! (And sorry for unnoticed) 

I know that your custom Kubernetes APIs are much better than APIs generated by openapi-generator/swagger-codegen directly, since I first used openapi-generator to generated codes, and which have some bugs. It was (but currently re-tackling) difficult to fix them using sed-like operations like kubernetes-client/gen.

But it's necessary to use APIs from kubernetes-client/gen for adding each language APIs to kubernetes-client. I'll try them on another branch.

I decided to use your APIs in this repository. Later, I'll apply the latest versions. Anyway, if there are not your efforts, I didn't start to develop Rust client. Thanks again :)

**Comment by ynqa** [comment]
@Arnavion Thanks for your comments!! (And sorry for unnoticed) 

I know that your custom Kubernetes APIs are much better than APIs generated by openapi-generator/swagger-codegen directly. I first used openapi-generator to generated codes, and which have some bugs and it was difficult to fix them using sed-like operations like kubernetes-client/gen.

But it's necessary to use APIs from kubernetes-client/gen for adding each language APIs to kubernetes-client. I'll try them on another branch.

I decided to use your APIs in this repository. Later, I'll apply the latest versions. Anyway, if there are not your efforts, I didn't start to develop Rust client. Thanks again :)

**Comment by ynqa** [comment]
@Arnavion Thanks for your comments!! (And sorry for unnoticed) 

I know that your custom Kubernetes APIs are much better than APIs generated by openapi-generator/swagger-codegen directly. I first used openapi-generator to generated codes, and which have some bugs and it was difficult to fix them using sed-like operations like kubernetes-client/gen.

But it's necessary to use APIs from kubernetes-client/gen for adding each language APIs to kubernetes-client. I'll try them on another branch.

Finally, I decided to use your APIs in this repository. Later, I'll apply the latest versions. Anyway, if there are not your efforts, I didn't start to develop Rust client. Thanks again :)

**Comment by ynqa** [comment]
@Arnavion Thanks for your comments!! (And sorry for unnoticed) 

I know that Kubernetes APIs from your custom generator are much better codes than generated by openapi-generator/swagger-codegen directly. Because I first used openapi-generator to generated codes, and which have some bugs and I found it was difficult to fix them using sed-like operations like kubernetes-client/gen.

But it's necessary to use APIs from kubernetes-client/gen for adding each language APIs to kubernetes-client. I'll try them on another branch.

Finally, I decided to use your APIs in this repository. Anyway, if there are not your efforts, I didn't start to develop Rust client. Thanks again :)

**Pull request closed without merging**
